CRUD/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('crudapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crudapp/urls.py
from django.urls import path
from . import views
from . views import StudentDeleteView, StudentUpdateView,\
	StudentListView, StudentCreateView

app_name = 'crudapp'

urlpatterns = [
	path('', StudentListView.as_view(), name='index'),
	#path('add_student/', views.add_student, name='add_student'),
	path('<int:pk>/delete/', StudentDeleteView.as_view(), name='delete'),
	path('<int:pk>/update/', StudentUpdateView.as_view(), name='update'),
	path('add_student/', StudentCreateView.as_view(), name='add_student'),
]

crudapp/models.py
from django.db import models
from django.shortcuts import reverse


# Create your models here.
class Student(models.Model):
	firstname = models.CharField(max_length=20)
	lastname = models.CharField(max_length=20)
	adm_no = models.IntegerField()
	passport = models.FileField()

	def get_absolute_url(self):
		return reverse('crudapp:index')

	def __str__(self):
		return self.firstname

crudapp/forms.py
from django import forms
from . models import Student


class StudentForm(forms.ModelForm):

	class Meta:
		model = Student
		fields = '__all__'

crudapp/views.py
from django.shortcuts import render, reverse, redirect
from . models import Student
from . forms import StudentForm
from django.views.generic import DeleteView,\
	UpdateView, ListView, CreateView


# Create your views here.
class StudentListView(ListView):
	model = Student
	template_name = 'crudapp/index.html'
	context_object_name = 'students'

"""
def add_student(request):
	form = StudentForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		student = form.save(commit=False)
		student.passport = request.FILES['passport']
		student.save()
		students = Student.objects.all()
		return render(request, 'crudapp/index.html', {'students': students})
	return render(request, 'crudapp/add_student.html', {'form': form})
"""


class StudentCreateView(CreateView):
	model = Student
	fields = ['firstname', 'lastname', 'adm_no', 'passport']
	template_name = 'crudapp/add_student.html'


class StudentDeleteView(DeleteView):
	model = Student
	success_url = '/'


class StudentUpdateView(UpdateView):
	model = Student
	fields = ['firstname', 'lastname', 'adm_no', 'passport']

	def get_success_url(self):
		return reverse('crudapp:index')

	def form_valid(self, form):
		return super().form_valid(form)

crudapp/templates/crudapp/add_student.html
{% extends 'crudapp/base.html' %}
{% block body %}
    <div class="row">
        <div class="page-header">
            <h3 class="text-primary" style="padding-left: 8%;"><strong>New Student</strong> {{ object.firstname }}</h3>
        </div>
    </div>
    <div class="row">
<form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'crudapp/form-template.html' %}

    <div class="form-group" style="padding-left: 18%;">
    <button type="submit" class="btn btn-info">Submit</button>
    </div>
</form>
    </div>
{% endblock %}

crudapp/templates/crudapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Django-CRUD{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="#"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'crudapp:index' %}">Django-CRUD</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class=""><a href="{% url 'crudapp:index' %}"><span class="glyphicon glyphicon-signal" aria-hidden="true"></span>&nbsp; Students</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'crudapp:add_student' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Student
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>

<div class="container">
{% block body %}
{% endblock %}
</div>
</body>
</html>

crudapp/templates/crudapp/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

crudapp/templates/crudapp/index.html
{%  extends 'crudapp/base.html' %}

{% block body %}
    <div class="row">
        <div class="page-header">
            <h3 class="text-center text-primary"><strong>Students</strong></h3>
        </div>
    </div>

    <div class="row">
        <table class="table">
            <thead>
            <th>No.</th>
            <th>First Name</th><th>Last Name</th>
            <th>Admission</th><th>Passport</th><th>Action</th>
            </thead>

            <tbody>
            {% if students %}
                {% for student in students %}
                    <tr>
                    <td>{{ student.id }}</td>
                    <td>{{ student.firstname }}</td>
                    <td>{{ student.lastname }}</td>
                    <td>{{ student.adm_no }}</td>
                    <td><img src="{{ student.passport.url }}" alt="" style="height: 50px; width: 50px;"> </td>
                    <td><a href="{% url 'crudapp:update' student.id %}" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-pencil"></span>Update</a>&nbsp;<a href="{% url 'crudapp:delete' student.id %}" class="btn btn-danger btn-sm"><span class="glyphicon glyphicon-trash"></span>Delete</a>  </td>
                    </tr>
                {% endfor %}
            {% endif %}
            </tbody>
        </table>
    </div>
{% endblock %}

crudapp/templates/crudapp/student_confirm_delete.html
{% extends 'crudapp/base.html' %}
{% block body %}
    <div class="row">
        <div class="page-header">
            <h3 class="text-danger"><strong>Delete</strong> {{ object.firstname }}</h3>
        </div>
    </div>
    <div class="row">
<form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <h4 class="">Are you sure you want to Delete?</h4>
        <button type="submit" class="btn btn-warning">Delete</button>
        <a href="{% url 'crudapp:index' %}" class="btn btn-info">Cancel</a>
    </div>
    {% include 'crudapp/form-template.html' %}

</form>
    </div>
{% endblock %}

crudapp/templates/crudapp/student_form.html
{% extends 'crudapp/base.html' %}

{% block body %}
<div class="row">
        <div class="page-header">
            <h3 class="text-primary" style="padding-left: 8%;"><strong>Update</strong> {{ object.firstname }}</h3>
        </div>
    </div>
    <div class="row">
<form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'crudapp/form-template.html' %}

    <div class="form-group" style="padding-left: 18%;">
    <button type="submit" class="btn btn-info">Update</button>
    </div>
</form>
    </div>
{% endblock %}